# version: '3.8'

services:  

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Compag*87
      MYSQL_DATABASE: mlflow
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mlflow/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mlops_net

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest # server /data --console-address ":9001"
    entrypoint: /bin/sh
    command: >
      -c "
      minio server /data --console-address ':9001' &
      sleep 10 &&
      mc alias set local http://localhost:9000 admin supersecret &&
      mc mb -p local/mlflows3 || true &&
      tail -f /dev/null
      "
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersecret
    ports:
      - "9000:9000"   # API de objetos
      - "8083:9001"   # Consola web
    volumes:
      - ./minio:/data
    restart: unless-stopped
    networks:
      - mlops_net
  
  mlflow_serv:
    build:
      context: ./mlflow
      dockerfile: dockerfile_mlflow
    container_name: mlflow_server
    ports:
      - "8084:5000"
    command: >
      mlflow server
      --backend-store-uri mysql+pymysql://root:Compag*87@mysql:3306/mlflow
      --default-artifact-root s3://mlflows3
      --host 0.0.0.0
      --port 5000
      --serve-artifacts
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://localhost:9000
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: supersecret
      MLFLOW_ARTIFACT_URI: s3://mlflows3
    depends_on:
      minio:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mlops_net

volumes:
  mysql_data:
  minio_data:

networks:
  mlops_net:
    external: true