version: '3.8'

services:

  fastapi:
    image: johnsanchez27/app-back:latest
    container_name: fastapi-server
    ports:
      - "8000:8000"

    environment:
      - MYSQL_HOST=ttp://10.43.101.200:31306
      - PYTHONUNBUFFERED=1
      - TZ=America/Bogota
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=supersecret
      - MLFLOW_S3_ENDPOINT_URL=http://10.43.101.200:31900
  

  streamlit:
    image: johnsanchez27/app-front:latest
    container_name: frontend-server
    ports:
      - "8501:8501"
    environment:
      - MYSQL_HOST=10.43.101.200:31306
      - PYTHONUNBUFFERED=1
      - TZ=America/Bogota
  


