version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: app_back/dockerfile_api
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - PYTHONUNBUFFERED=1
      - TZ=America/Bogota
    networks:
      - mlops_net

  streamlit:
    build:
      context: .
      dockerfile: app_front/dockerfile_stream
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      - MYSQL_HOST=mysql
      - PYTHONUNBUFFERED=1
      - TZ=America/Bogota
    networks:
      - mlops_net

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Compag*87
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mlops_net


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mlops_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - mlops_net

networks:
  mlops_net:
    driver: bridge

volumes:
  mysql_data:
  grafana_data:
