apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-composeMonitoreo.yml -o komposeMonitoreo/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  type: NodePort 
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 31300
  selector:
    io.kompose.service: grafana
status:
  loadBalancer: {}
