apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o komposefilesback/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o komposefilesback/ --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: streamlit
    spec:
      containers:
        - env:
            - name: MYSQL_HOST
              value: 10.43.101.200:31306
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: TZ
              value: America/Bogota
          image: johnsanchez27/app-front:latest
          name: frontend-server
          ports:
            - containerPort: 8501
          resources: {}
      restartPolicy: Always
status: {}
