apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o manifestsBack/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: fastapi
  name: fastapi
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
      nodePort : 31800
  selector:
    io.kompose.service: fastapi
