apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o manifestsBack/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: fastapi
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fastapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o manifestsBack/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: fastapi
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: supersecret
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://10.43.101.200:31900
            - name: MYSQL_HOST
              value: ttp://10.43.101.200:31306
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: TZ
              value: America/Bogota
          image: johnsanchez27/app-fast:v2
          name: fastapi-server
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
