apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o manifestsBack/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o manifestsBack/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: streamlit
    spec:
      containers:
        - env:
            - name: MYSQL_HOST
              value: 10.43.101.200:31306
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: TZ
              value: America/Bogota
          image: johnsanchez27/app-front:v2
          name: frontend-server
          ports:
            - containerPort: 8501
              protocol: TCP
      restartPolicy: Always
