apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o manifestsBack/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: streamlit
  name: streamlit
spec:
  type : NodePort
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
      nodePort : 31851
  selector:
    io.kompose.service: streamlit
