apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-composemlflow.yml -o komposefiles/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-composemlflow.yml -o komposefiles/ --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - -c
            - ' minio server /data --console-address '':9001'' & sleep 10 && mc alias set local http://localhost:9000 admin supersecret && mc mb -p local/mlflows3 || true && tail -f /dev/null '
          command:
            - /bin/sh
          env:
            - name: MINIO_ROOT_PASSWORD
              value: supersecret
            - name: MINIO_ROOT_USER
              value: admin
          image: quay.io/minio/minio:latest
          name: minio
          ports:
            - containerPort: 9000
            - containerPort: 9001
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: minio-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/estudiante/Documents/proyecto_final/MLOps_Proyecto_Final/minio
          name: minio-hostpath0
status: {}
