apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-composemlflow.yml -o komposefiles/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mlflow-serv
  name: mlflow-serv
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mlflow-serv
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-composemlflow.yml -o komposefiles/ --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mlflow-serv
    spec:
      containers:
        - args:
            - mlflow
            - server
            - --backend-store-uri
            - mysql+pymysql://root:Compaq*87@10.43.101.200:31306/mlflow
            - --default-artifact-root
            - s3://mlflows3
            - --host
            - 0.0.0.0
            - --port
            - "5000"
            - --serve-artifacts
          env:
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: supersecret
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://10.43.101.200:31900
          image: johnsanchez27/mlflow-api:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:5000/health
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: mlflow-server
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
