apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-composemlflow.yml -o komposefiles/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-server
  name: mysql-server
spec:
  type: NodePort 
  ports:
    - name: "8082"
      port: 8082
      targetPort: 3306
      nodePort: 31306
  selector:
    io.kompose.service: mysql-server
status:
  loadBalancer: {}
