name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push app-front image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-front:latest ./app-front
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-front:latest

    - name: Build and push app-fast image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-fast:latest ./app-fast
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-fast:latest

    - name: Build and push mysql-api image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mysql-api:latest ./mysql-api
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mysql-api:latest

    - name: Build and push mlflow-api image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-api:latest ./mlflow-api
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-api:latest
